<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Zero1\PosPayCash\Block\Info\PosPayCash
 */
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<div class="order-payment-method-name"><?= $block->escapeHtml($paymentTitle) ?></div>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?= $block->escapeHtml(__('Cash tendered')) ?>:</th>
        <td><?= $block->escapeHtml($block->getInfo()->getOrder()->getPayment()->getAdditionalInformation('cash_tendered')) ?></td>
    </tr>
</table>
